apiVersion: v1
kind: Service
metadata:
  name: json-server-service
  labels:
    app: json-server-devops-project
spec:
  selector:
    app: json-server-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
